
// get  data
export const LOAD_PRODUCTS_DATA_START="LOAD_PRODUCTS_DATA_START"
export const LOAD_PRODUCTS_DATA_SUCCESS="LOAD_PRODUCTS_DATA_SUCCESS"
export const LOAD_PRODUCTS_DATA_ERROR="LOAD_PRODUCTS_DATA_ERROR"


//email&password login
 
export const EMAILANDPASSWORD_LOGIN_START = " EMAILANDPASSWORD_LOGIN_START"
export const EMAILANDPASSWORD_LOGIN_SUCCESS = " EMAILANDPASSWORD_LOGIN_SUCCESS"
export const EMAILANDPASSWORD_LOGIN_ERROR = " EMAILANDPASSWORD_LOGIN_ERROR"

//email&password signup
export const EMAILANDPASSWORD_SIGNUP_START ="EMAILANDPASSWORD_SIGNUP_START"
export const EMAILANDPASSWORD_SIGNUP_SUCCESS ="EMAILANDPASSWORD_SIGNUP_SUCCESS"
export const EMAILANDPASSWORD_SIGNUP_ERROR ="EMAILANDPASSWORD_SIGNUP_ERROR"

//google

export const GOOGLE_LOGIN_START = " GOOGLE_LOGIN_START"
export const GOOGLE_LOGIN_SUCCESS = " GOOGLE_LOGIN_SUCCESS"
export const GOOGLE_LOGIN_ERROR = " GOOGLE_LOGIN_ERROR"

//phonenumber

export const PHONENUMBER_LOGIN_START = " PHONENUMBER_LOGIN_START"
export const PHONENUMBER_LOGIN_SUCCESS = " PHONENUMBER_LOGIN_SUCCESS"
export const PHONENUMBER_LOGIN_ERROR = " PHONENUMBER_LOGIN_ERROR"

//searchpalce

export const SEARCH_PLACE_START = " SEARCH_PLACE_START"
export const SEARCH_PLACE_SUCCESS = " SEARCH_PLACE_SUCCESS"
export const SEARCH_PLACE_ERROR = " SEARCH_PLACE_ERROR"

//falsgpage

export const LOAD_FLASH_PAGE_IMAGES_START ="LOAD_FLASH_PAGE_IMAGES_START"
export const LOAD_FLASH_PAGE_IMAGES_SUCCESS = " LOAD_FLASH_PAGE_IMAGES_SUCCESS"
export const LOAD_FLASH_PAGE_IMAGES_ERROR = " LOAD_FLASH_PAGE_IMAGES_ERROR"




export const LOAD_PAST_IMAGES_START="LOAD_PAST_IMAGES_START"
export const LOAD_PAST_IMAGES_SUCCESS="LOAD_PAST_IMAGES_SUCCESS"
export const LOAD_PAST_IMAGES_ERROR="LOAD_PAST_IMAGES_ERROR"